#issues solved:
# - create task uri to test webservers
- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for writing smoke test in prod environment.
    uri:
      url: http://localhost
      return_content: yes
    register: website

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in website.content"

