---
# handlers file for app-tier
- name: start_appservice
  service:
    name: "{{ appservice }}"
    state: started

- name: restart_appservice
  service:
    name: "{{ appservice }}"
    state:  restarted
