---
# tasks file for app-tier
- name: install {{ appservice }}
  yum:
    name: "{{ appservice }}"
    state: latest

- name: enable {{ appservice }} at boot
  service:
    name: "{{ appservice }}"
    enabled: yes
  notify: start_appservice

- name: start appservice
  service:
    name: "{{ appservice }}"
    state: started

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify: restart_appservice

- name: restart appservice
  service:
    name: tomcat
    state: "{{ appservice }}"
